name: Build and Push to Docker Hub

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile        # ✅ Corrigido de dockerfile → file
          push: true
          tags: moisesgc/webacademy:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Fazendo deploy
        run: echo "Deploy com sucesso!"
